### ISSUE TITLE
Problem solved

### ISSUE THREAD

**Issue by ghost** [iamshaunjp/graphql-playlist#12]
Here is my mutation defination code:
``
const addBookMutation = gql`
  mutation($name: String!, $genre: String!, $authorId: ID!){
    addBook(name: $name, genre: $genre, authorId: $authorId){
      name
      id
    }
  }
``

But I met a problem, it reports that 
> 
[GraphQL error]: Message: Unknown type "ID"., Location: [object Object], Path: undefined
index.js:75 
>

**Comment by ghost** [comment]
Problem solved

**Comment by camjackson** [comment]
@ohkatesroad I don't suppose you remember how you solved it, do you? I'm facing a very similar error at the moment.
